### ISSUE TITLE
Source of twiddler.cfg files

### ISSUE THREAD

**Issue by steveluc** [ivanwfr/Twiddler3-Layout#1]
Are there configuration files or software for creating configuration files somewhere in this repo?  Thanks.

**Comment by steveluc** [comment]
PS received Twiddler 3 yesterday.  Want to put best configuration on it before investing in training time.

**Comment by ivanwfr** [comment]
Sure, I've spent several weeks on this even before I received mine!

You have some here:
https://github.com/cswetenham/tabspace2.1

and on TekGear's tuner page:
http://twiddler.tekgear.com/tuner

**Comment by steveluc** [comment]
Great.  Have you tried loading the tabspace2.1 cfg file on your Twiddler 3?  Do you know of any format differences 3 from 2.1.  I talked with a TekGear representative who said he thought 3 is backward compatible.  Waiting to hear more.

Is there a way to edit config files with text instead of the web interface (tuner)?

Is there documentation of the config file format?

**Comment by ivanwfr** [comment]
Here is a link from TekGear on facebook:

## \- https://www.facebook.com/TekGearInc

http://twiddler.tekgear.com/tuner/publicshare.xhtml?file_id=Twiddler3_TabSpace_1418749449689_5

CFG file is binary and I don't know of any other way to generate one 
instead of using TekGear's tuner.
I just spent a few hours to build my own based on an update I made today 
to my layout on GitHub
\ http://ivanwfr.github.io/Twiddler3-Layout
...takes some doing but it works!

-ivan

**Comment by comods** [comment]
Can you reference that config file link near the beginning of the page: http://ivanwfr.github.io/Twiddler3-Layout/

With the link can you clarify if it is an unchanged tabspace from tekgear or if you have made improvements to it.

**Comment by steveluc** [comment]
Thanks for the info @ivanwfr.

**Comment by ivanwfr** [comment]
@RefinedSoftwareLLC
As this page is in no way a contribution to the official support, I'm going to add this reference into the TabSpace section. This layout is only my start point and it already has its own repository and maintainer.

And this should be taken care of by Tek Gear in the first place!! You should send them this request as well. Who knows, they may take the time to do more than send a post on twitter and facebook where I found it by chance ;-)

I'm not ready yet to think we are going to deal with a low grade support, mostly based on random contribution. I am still counting on some constructive dialog to come, involving the users, to get us a good resource base... When they are less busy with the hardware aspect of things!
