### ISSUE TITLE
I didn't see your layout on the Forums.

### ISSUE THREAD

**Issue by comods** [ivanwfr/Twiddler3-Layout#2]
Do you recommend people using your layout over the official tabspace one? 
If so, should your layout be listed at: http://forum.tekgear.com/c/Configs

**Comment by AlexBravo** [comment]
I do recommend it and it's here: http://forum.tekgear.com/t/backspice-layout-config-fw-0-09/45

**Comment by ivanwfr** [comment]
Hi, maybe, but I think having recommended enough from this page.
http://ivanwfr.github.io/Twiddler3-Layout/
As I must be the only one to have read it while I was writing, I don't care to advertise any more.
